# Site
repository:  GeorgeCiesinski/modern-resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: George Ciesinski
title: Software Developer
email: george.ciesin@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://GeorgeCiesinski.me
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: GeorgeCiesinski
github_username:  GeorgeCiesinski
stackoverflow_username: "2665812"
linkedin_username: george-ciesinski-5a8a134a

# Additional icon links
additional_links:
  - title: PDF Resume
    icon: far fa-file-pdf
    url: https://georgeciesinski.me/assets/PDF/GeorgeCiesinskiResume.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/self.png
about_content: | # this will include new lines to allow paragraphs
  I am a software developer currently working as an IT professional. As well as providing L1 phone and email support, I also have experience making different kinds of software and scripts. I have worked on numerous solo projects, as well as projects within a team.

  I am most skilled in: <mark>Python</mark> and <mark>Git</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Flask RESTful Api
        link: https://github.com/GeorgeCiesinski/FlaskRESTful-for-Heroku
        link_text: Github
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: https://github.com/GeorgeCiesinski/FlaskRESTful-for-Heroku
        quote: >
          A RESTful Api which lets you POST, GET, PUT, and DELETE various stores and items
        description: | # this will include new lines to allow paragraphs
          This API was built using <mark>Python</mark>, <mark>Flask</mark> and deployed to <mark>Heroku</mark>. I wrote this project to familiarize myself with <mark>Flask</mark> and dependent libraries such as <mark>Flask-JWT</mark> and <mark>Flask-SQLAlchemy</mark>.
      - layout: left
        title: Portfolio Website
        link: https://github.com/GeorgeCiesinski/FlaskRESTful-for-Heroku
        link_text: Github
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: https://github.com/GeorgeCiesinski/george-ciesinski-project-page
        quote: >
          Bootstrap 5 website displaying my various projects
        description: | # this will include new lines to allow paragraphs
          This website was built using <mark>HTML</mark>, <mark>CSS</mark>, <mark>Bootstrap 5</mark> and hosted with <mark>Github Pages</mark>.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: New Era Technology
        sub_title: VNOC / CSC Advocate
        caption: August 2017 - PRESENT
        link: https://www.neweratech.com/us/
        quote: >
          A video conferencing company that provides global support for various video teleconferencing services
        description: | # this will include new lines to allow paragraphs
          * Created application using Python that uses shortcuts to recall saved text responses, saving
          colleagues hundreds of hours after widespread adoption
          * Connect video conferences over global network  and provide live operator support
          * Investigate and resolve network and device issues
      - layout: left
        title: Humber College
        sub_title: IT Analyst
        caption: August 2015 - March 2017
        link: https://humber.ca/
        quote: >
          Institute of Technology & Advanced Learning
        description: | # this will include new lines to allow paragraphs
          * Provided over-counter support to staff and students to resolve technical issues
          * Provide technical troubleshooting by e-mail and phone
      - layout: left
        title: Multimatic
        sub_title: Jr. Database Administrator COOP
        caption: May 2013 - August 2013
        link: https://www.multimatic.com/
        quote: >
          A privately held Canadian corporation supplying components, systems and engineering services to the global automotive industry
        description: | # this will include new lines to allow paragraphs
          * Architected ETL process between two conflicting databases (MS Access, MySQL)
          * Linked Kepware to MySQL to track errors, states, and part counts
          * Researched alternative methods to link company databases (ODBC, VB Script)
  - title: Education
    layout: list
    content:
      - layout: left
        title: Humber College
        sub_title: Advanced Diploma in Electromechanical Engineering
        caption: 2011 - 2014
        quote: >
          Electro-mechanical Engineering Advanced Diploma
        description: | # this will include new lines to allow paragraphs
          * Programmed articulated robots and PLC (Ladder and Structured Text)
          * Learned various programming languages such as VB, C++, and C#
          * Developed an industrial 3D printer for my Final Year project
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      * Familiar with <mark>Python</mark>, <mark>Javascript</mark>, <mark>C++</mark>, <mark>C#</mark>, <mark>HTML</mark>, <mark>CSS</mark>, and <mark>SQL</mark>.
      * **Team Player**, **Problem Solver**, **Quick Learner**, **Creative** and **Optimistic**
  - title: Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I am not programming, enjoy staying active by cycling, tennis, squash, and practising martial arts.

      I also like exploring Sci-Fi / Fantasy media, and have a keen interest in cyberpunk themes.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
